
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class BillingPeriod
{

    public int BillingPeriodID { get; set; }

    public Nullable<int> PeriodNumber { get; set; }

    public Nullable<int> CalendarYear { get; set; }

    public Nullable<System.DateTime> PeriodEndDate { get; set; }

    public Nullable<int> PeriodClosedInd { get; set; }

    public string PeriodClosedBy { get; set; }

    public Nullable<System.DateTime> PeriodClosedDate { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

}

}
