
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public int CustomerID { get; set; }

    public string CustomerCode { get; set; }

    public string CustomerName { get; set; }

    public string DBAName { get; set; }

    public string ShortName { get; set; }

    public Nullable<int> MainAddressID { get; set; }

    public Nullable<int> BillingAddressID { get; set; }

    public string CustomerType { get; set; }

    public string CustomerSubType { get; set; }

    public string VendorNumber { get; set; }

    public string LoadNumberPrefix { get; set; }

    public Nullable<int> LoadNumberLength { get; set; }

    public Nullable<int> NextLoadNumber { get; set; }

    public string InternalComment { get; set; }

    public string DriverComment { get; set; }

    public Nullable<int> CollectionsIssueInd { get; set; }

    public Nullable<int> SortOrder { get; set; }

    public Nullable<int> AlwaysShowInWIPInd { get; set; }

    public Nullable<int> EligibleForAutoLoadConfigInd { get; set; }

    public Nullable<int> ApplyFuelSurchargeInd { get; set; }

    public Nullable<int> FSPOverrideInd { get; set; }

    public Nullable<decimal> FuelSurchargePercent { get; set; }

    public string DefaultBillingMethod { get; set; }

    public Nullable<int> BulkBillingInd { get; set; }

    public Nullable<int> DoNotPrintInvoiceInd { get; set; }

    public Nullable<int> DoNotExportInvoiceInfoInd { get; set; }

    public Nullable<int> NewCustomerInd { get; set; }

    public string RecordStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<int> PortStorageCustomerInd { get; set; }

    public Nullable<int> RequiresPONumberInd { get; set; }

    public Nullable<int> AutoportExportCustomerInd { get; set; }

    public Nullable<int> SendEmailConfirmationsInd { get; set; }

    public Nullable<int> AssignedToExternalCollectionsInd { get; set; }

    public string CustomerOf { get; set; }

    public Nullable<int> STIFollowupRequiredInd { get; set; }

    public string BookingNumberPrefix { get; set; }

    public string HandheldScannerCustomerCode { get; set; }

    public Nullable<int> HideNewFreightFromBrokersInd { get; set; }

    public Nullable<int> DamagePhotoRequiredInd { get; set; }

}

}
