//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWorksService.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerStorageRequest
    {
        public int requestId { get; set; }
        public string requestedBy { get; set; }
        public Nullable<System.DateTime> dateRequested { get; set; }
        public Nullable<System.DateTime> estPickupTime { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datePrinted { get; set; }
        public string printedBy { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> dealerPrint { get; set; }
        public Nullable<int> generateNotification { get; set; }
    }
}
