
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class ErrorLog
{

    public int Id { get; set; }

    public string SystemMac { get; set; }

    public System.DateTime DateTime { get; set; }

    public string Thread { get; set; }

    public string Level { get; set; }

    public string Logger { get; set; }

    public string Ndc { get; set; }

    public string Message { get; set; }

    public string BuildVersion { get; set; }

}

}
