
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class Leg
{

    public int LegsID { get; set; }

    public Nullable<int> VehicleID { get; set; }

    public Nullable<int> RunID { get; set; }

    public Nullable<int> LoadID { get; set; }

    public Nullable<int> PoolID { get; set; }

    public Nullable<System.DateTime> DateAvailable { get; set; }

    public Nullable<int> PickupLocationID { get; set; }

    public Nullable<System.DateTime> PickupDate { get; set; }

    public Nullable<int> DropoffLocationID { get; set; }

    public Nullable<System.DateTime> DropoffDate { get; set; }

    public Nullable<int> OutsideCarrierLegInd { get; set; }

    public Nullable<int> OutsideCarrierID { get; set; }

    public Nullable<int> OutsideCarrierPaymentMethod { get; set; }

    public Nullable<decimal> OutsideCarrierPercentage { get; set; }

    public Nullable<decimal> OutsideCarrierPay { get; set; }

    public Nullable<decimal> OutsideCarrierFuelSurchargePercentage { get; set; }

    public Nullable<int> OCFSPEstablishedInd { get; set; }

    public Nullable<int> LegNumber { get; set; }

    public Nullable<int> FinalLegInd { get; set; }

    public string LegStatus { get; set; }

    public Nullable<int> ShagUnitInd { get; set; }

    public Nullable<int> ReservedByDriverInd { get; set; }

    public Nullable<int> ReservedByDriverID { get; set; }

    public Nullable<int> ExceptionInd { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public string SignatureFileName { get; set; }

    public string SignedBy { get; set; }

    public string NoSignatureReasonCode { get; set; }

    public string DeliveryBayLocation { get; set; }

    public Nullable<int> OutsideCarrierFuelSurchargeType { get; set; }

    public string DriverSignatureFileName { get; set; }

    public Nullable<int> PickupBillOfLadingID { get; set; }

    public Nullable<int> DropoffBillOfLadingID { get; set; }

}

}
