
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class Load
{

    public int LoadsID { get; set; }

    public Nullable<int> DriverID { get; set; }

    public string LoadNumber { get; set; }

    public string CustomerLoadNumber { get; set; }

    public Nullable<int> LoadSize { get; set; }

    public Nullable<int> NumberLoaded { get; set; }

    public Nullable<int> NumberDelivered { get; set; }

    public Nullable<int> OutsideCarrierLoadInd { get; set; }

    public Nullable<int> OutsideCarrierID { get; set; }

    public Nullable<System.DateTime> ScheduledPickupDate { get; set; }

    public Nullable<System.DateTime> ActualPickupDate { get; set; }

    public Nullable<System.DateTime> ScheduledDeliveryDate { get; set; }

    public Nullable<System.DateTime> ActualDeliveryDate { get; set; }

    public Nullable<int> RunID { get; set; }

    public string ControlNumber { get; set; }

    public Nullable<int> LoadGroup { get; set; }

    public Nullable<int> ProcessingOrder { get; set; }

    public string LoadLane { get; set; }

    public string LoadStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<System.DateTime> ProductionDate { get; set; }

    public Nullable<int> HotLoadInd { get; set; }

    public Nullable<decimal> EstimatedPayMiles { get; set; }

    public string LoadType { get; set; }

}

}
