//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWorksService.DAL.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PortalDbEntities : DbContext
    {
        public PortalDbEntities()
            : base("name=PortalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DealerStorageRequest> DealerStorageRequests { get; set; }
        public virtual DbSet<DealerStorageRequestItem> DealerStorageRequestItems { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleUser> ModuleUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleMember> RoleMembers { get; set; }
        public virtual DbSet<SysProperty> SysProperties { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserCustomerRole> UserCustomerRoles { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    
        public virtual ObjectResult<spGetSelectedUserCustomerList_Result> spGetSelectedUserCustomerList(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSelectedUserCustomerList_Result>("spGetSelectedUserCustomerList", userIDParameter);
        }
    }
}
