
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class PortStorageVehiclesImport
{

    public int PortStorageVehiclesImportID { get; set; }

    public Nullable<int> BatchID { get; set; }

    public string DateIn { get; set; }

    public string DealerCode { get; set; }

    public string VIN { get; set; }

    public string ModelYear { get; set; }

    public string ModelName { get; set; }

    public string Color { get; set; }

    public string Location { get; set; }

    public Nullable<int> ImportedInd { get; set; }

    public Nullable<System.DateTime> ImportedDate { get; set; }

    public string ImportedBy { get; set; }

    public string RecordStatus { get; set; }

    public string VehicleYear { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Bodystyle { get; set; }

    public string VehicleLength { get; set; }

    public string VehicleWidth { get; set; }

    public string VehicleHeight { get; set; }

    public Nullable<int> VINDecodedInd { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public string FileName { get; set; }

    public string DamageCodeList { get; set; }

}

}
