
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class PortStorageVehicleLocationImport
{

    public int PortStorageVehicleLocationImportID { get; set; }

    public Nullable<int> BatchID { get; set; }

    public string VIN { get; set; }

    public string Location { get; set; }

    public Nullable<int> ImportedInd { get; set; }

    public Nullable<System.DateTime> ImportedDate { get; set; }

    public string ImportedBy { get; set; }

    public string RecordStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public string FileName { get; set; }

}

}
