
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class PSVehicleDamageDetail
{

    public int PSVehicleDamageDetailID { get; set; }

    public Nullable<int> PSDamageClaimID { get; set; }

    public Nullable<int> PSVehicleInspectionID { get; set; }

    public string ClaimNumber { get; set; }

    public Nullable<int> PortStorageVehiclesID { get; set; }

    public string DamageCode { get; set; }

    public string DamageDescription { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

}

}
