//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWorksService.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMember
    {
        public int rolememberId { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string whoCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string whoUpdated { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
