
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class SettingTable
{

    public int SettingTableID { get; set; }

    public string ValueKey { get; set; }

    public string ValueDescription { get; set; }

    public Nullable<int> ShareWithMobileInd { get; set; }

    public Nullable<int> AllowChangeByAdminInd { get; set; }

    public string SettingName { get; set; }

    public string Description { get; set; }

    public string DataType { get; set; }

    public string DataSubType { get; set; }

    public Nullable<int> DAIOnlyInd { get; set; }

    public string RecordStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<int> StaticValueInd { get; set; }

}

}
