
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int UserID { get; set; }

    public string UserCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Password { get; set; }

    public string PIN { get; set; }

    public string Phone { get; set; }

    public string PhoneExtension { get; set; }

    public string CellPhone { get; set; }

    public string FaxNumber { get; set; }

    public string EmailAddress { get; set; }

    public Nullable<decimal> LabelXOffset { get; set; }

    public Nullable<decimal> LabelYOffset { get; set; }

    public string IMEI { get; set; }

    public Nullable<System.DateTime> LastConnection { get; set; }

    public Nullable<int> datsVersion { get; set; }

    public string RecordStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public string EmployeeNumber { get; set; }

    public string PortPassIDNumber { get; set; }

    public string Department { get; set; }

    public Nullable<decimal> StraightTimeRate { get; set; }

    public Nullable<decimal> PieceRateRate { get; set; }

    public Nullable<decimal> PDIRate { get; set; }

    public Nullable<decimal> FlatBenefitPayRate { get; set; }

    public string AlternateEmailAddress { get; set; }

}

}
