
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class UserLoginLog
{

    public int UserLoginLogID { get; set; }

    public string UserCode { get; set; }

    public Nullable<System.DateTime> LoginDate { get; set; }

    public Nullable<int> SPID { get; set; }

    public string HostName { get; set; }

    public Nullable<System.DateTime> BuildDate { get; set; }

}

}
