
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class Vehicle
{

    public int VehicleID { get; set; }

    public Nullable<int> CustomerID { get; set; }

    public Nullable<int> OrderID { get; set; }

    public string VehicleYear { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Bodystyle { get; set; }

    public string VIN { get; set; }

    public string Color { get; set; }

    public string VehicleLength { get; set; }

    public string VehicleWidth { get; set; }

    public string VehicleHeight { get; set; }

    public Nullable<int> PickupLocationID { get; set; }

    public string PickupLocationType { get; set; }

    public Nullable<int> DropoffLocationID { get; set; }

    public string DropoffLocationType { get; set; }

    public string VehicleStatus { get; set; }

    public string VehicleLocation { get; set; }

    public string CustomerIdentification { get; set; }

    public string SizeClass { get; set; }

    public string BayLocation { get; set; }

    public string RailCarNumber { get; set; }

    public Nullable<int> PriorityInd { get; set; }

    public string HaulType { get; set; }

    public Nullable<System.DateTime> AvailableForPickupDate { get; set; }

    public Nullable<int> ShopWorkStartedInd { get; set; }

    public Nullable<System.DateTime> ShopWorkStartedDate { get; set; }

    public Nullable<int> ShopWorkCompleteInd { get; set; }

    public Nullable<System.DateTime> ShopWorkCompleteDate { get; set; }

    public Nullable<System.DateTime> PaperworkReceivedDate { get; set; }

    public string ICLAuditCode { get; set; }

    public Nullable<System.DateTime> IntoInventoryDate { get; set; }

    public Nullable<decimal> ChargeRate { get; set; }

    public Nullable<int> ChargeRateOverrideInd { get; set; }

    public Nullable<int> BilledInd { get; set; }

    public Nullable<int> BillingID { get; set; }

    public Nullable<System.DateTime> DateBilled { get; set; }

    public Nullable<int> VINDecodedInd { get; set; }

    public string RecordStatus { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public Nullable<int> CreditHoldInd { get; set; }

    public string CreditHoldBy { get; set; }

    public string ReleaseCode { get; set; }

    public Nullable<int> PickupNotificationSentInd { get; set; }

    public Nullable<int> STIDeliveryNotificationSentInd { get; set; }

    public Nullable<int> DAIDATBillingID { get; set; }

    public Nullable<int> BillOfLadingSentInd { get; set; }

    public Nullable<int> DealerHoldOverrideInd { get; set; }

    public string Note { get; set; }

    public Nullable<decimal> MiscellaneousAdditive { get; set; }

    public Nullable<decimal> FuelSurcharge { get; set; }

    public string ShopWorkStartedBy { get; set; }

    public string ShopWorkCompleteBy { get; set; }

    public Nullable<int> AccessoriesCompleteInd { get; set; }

    public Nullable<System.DateTime> AccessoriesCompleteDate { get; set; }

    public string AccessoriesCompleteBy { get; set; }

    public Nullable<int> PDICompleteInd { get; set; }

    public Nullable<System.DateTime> PDICompleteDate { get; set; }

    public string PDICompleteBy { get; set; }

    public Nullable<int> FinalShipawayInspectionDoneInd { get; set; }

    public Nullable<System.DateTime> FinalShipawayInspectionDate { get; set; }

    public string FinalShipawayInspectionDoneBy { get; set; }

    public Nullable<System.DateTime> DealerETADate { get; set; }

    public Nullable<System.DateTime> EstimatedReleaseDate { get; set; }

    public Nullable<System.DateTime> DateMadeAvailable { get; set; }

    public string CurrencyCountryCode { get; set; }

    public Nullable<decimal> Tax { get; set; }

    public string OriginSPLC { get; set; }

    public string DestinationSPLC { get; set; }

    public Nullable<int> SpotBuyUnitInd { get; set; }

}

}
