
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppWorksService.DAL.Edmx
{

using System;
    using System.Collections.Generic;
    
public partial class VINDecode
{

    public int VINDecodeID { get; set; }

    public string VINSquish { get; set; }

    public string VehicleYear { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Bodystyle { get; set; }

    public string VehicleLength { get; set; }

    public string VehicleWidth { get; set; }

    public string VehicleHeight { get; set; }

    public string VehicleWeight { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<decimal> PayRate { get; set; }

}

}
