//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWorks.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWorks.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string ActionSave {
            get {
                return ResourceManager.GetString("ActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string ActionUpdate {
            get {
                return ResourceManager.GetString("ActionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Role.
        /// </summary>
        public static string DefaultRole {
            get {
                return ResourceManager.GetString("DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role already assigned..
        /// </summary>
        public static string ErrorAlreadyRoleAsign {
            get {
                return ResourceManager.GetString("ErrorAlreadyRoleAsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please enter credentials (max 20 and min 4) .
        /// </summary>
        public static string ErrorCredentialLenght {
            get {
                return ResourceManager.GetString("ErrorCredentialLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while editing the damage code.
        /// </summary>
        public static string ErrorDamageCode {
            get {
                return ResourceManager.GetString("ErrorDamageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Deleting Records!.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert Duplicate Code and CodeType.
        /// </summary>
        public static string ErrorDuplicateCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email Address..
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a PIN..
        /// </summary>
        public static string ErrorEmptyPin {
            get {
                return ResourceManager.GetString("ErrorEmptyPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Code..
        /// </summary>
        public static string ErrorEmptyUserCode {
            get {
                return ResourceManager.GetString("ErrorEmptyUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a code.
        /// </summary>
        public static string ErrorEnterCode {
            get {
                return ResourceManager.GetString("ErrorEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error inserting Record .
        /// </summary>
        public static string ErrorInserted {
            get {
                return ResourceManager.GetString("ErrorInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Roles assigned. Please contact the System Administrator.
        /// </summary>
        public static string ErrorNoRoleAsign {
            get {
                return ResourceManager.GetString("ErrorNoRoleAsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank.
        /// </summary>
        public static string ErrorPasswordText {
            get {
                return ResourceManager.GetString("ErrorPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed. Please check error logs.
        /// </summary>
        public static string ErrorToUpdate {
            get {
                return ResourceManager.GetString("ErrorToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usercode already exists .
        /// </summary>
        public static string ErrorUserCode {
            get {
                return ResourceManager.GetString("ErrorUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password cannot be blank .
        /// </summary>
        public static string ErrorUsernameAndPasswordText {
            get {
                return ResourceManager.GetString("ErrorUsernameAndPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank .
        /// </summary>
        public static string ErrorUsernameText {
            get {
                return ResourceManager.GetString("ErrorUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string ErrorWrongCredential {
            get {
                return ResourceManager.GetString("ErrorWrongCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string InsertAll {
            get {
                return ResourceManager.GetString("InsertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound inspection.
        /// </summary>
        public static string InspectionType1 {
            get {
                return ResourceManager.GetString("InspectionType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound inspection.
        /// </summary>
        public static string InspectionType2 {
            get {
                return ResourceManager.GetString("InspectionType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard inspection.
        /// </summary>
        public static string InspectionType3 {
            get {
                return ResourceManager.GetString("InspectionType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End {2} function ::{0} {1}..
        /// </summary>
        public static string loggerMsgEnd {
            get {
                return ResourceManager.GetString("loggerMsgEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called {2} function ::{0} {1}..
        /// </summary>
        public static string loggerMsgStart {
            get {
                return ResourceManager.GetString("loggerMsgStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&gt;&gt;Add User.
        /// </summary>
        public static string menuAddUser {
            get {
                return ResourceManager.GetString("menuAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string menuAdmin {
            get {
                return ResourceManager.GetString("menuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&gt;&gt;Billing Period Admin.
        /// </summary>
        public static string menuBillingPeriodAdmin {
            get {
                return ResourceManager.GetString("menuBillingPeriodAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&gt;&gt;Code Admin.
        /// </summary>
        public static string menuCodeAdmin {
            get {
                return ResourceManager.GetString("menuCodeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&gt;&gt;Customer Admin.
        /// </summary>
        public static string menuCustAdmin {
            get {
                return ResourceManager.GetString("menuCustAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string menuDashBoard {
            get {
                return ResourceManager.GetString("menuDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage&gt;&gt;Date Out Processing.
        /// </summary>
        public static string menuDateoutProcessing {
            get {
                return ResourceManager.GetString("menuDateoutProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin&gt;&gt;Find User.
        /// </summary>
        public static string menuFindUser {
            get {
                return ResourceManager.GetString("menuFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage&gt;&gt;Generate Invoices.
        /// </summary>
        public static string menuGenInvoice {
            get {
                return ResourceManager.GetString("menuGenInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage.
        /// </summary>
        public static string menuPortStorage {
            get {
                return ResourceManager.GetString("menuPortStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage&gt;&gt;Reports.
        /// </summary>
        public static string menuPSReports {
            get {
                return ResourceManager.GetString("menuPSReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage&gt;&gt;Add/Edit PS Records.
        /// </summary>
        public static string menuPSVehicle {
            get {
                return ResourceManager.GetString("menuPSVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Storage&gt;&gt;Request Processing.
        /// </summary>
        public static string menuRequestProcessing {
            get {
                return ResourceManager.GetString("menuRequestProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        public static string menuSyatemAdmin {
            get {
                return ResourceManager.GetString("menuSyatemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MsgAll {
            get {
                return ResourceManager.GetString("MsgAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate invoices for the selected customers ?.
        /// </summary>
        public static string MsgApproveConfirm {
            get {
                return ResourceManager.GetString("MsgApproveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a batch to Continue.
        /// </summary>
        public static string msgBatchReq {
            get {
                return ResourceManager.GetString("msgBatchReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the main billing line item.
        /// </summary>
        public static string msgBillingError {
            get {
                return ResourceManager.GetString("msgBillingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error inserting the Billing Line Items record.
        /// </summary>
        public static string msgBillingLineError {
            get {
                return ResourceManager.GetString("msgBillingLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Calendar Year and Period Number that you entered already exists. You must enter unique combination of calendar year and Period Number.
        /// </summary>
        public static string msgCalanderYearPerodNumberAlredy {
            get {
                return ResourceManager.GetString("msgCalanderYearPerodNumberAlredy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a calendar year.
        /// </summary>
        public static string msgCalanderYearReq {
            get {
                return ResourceManager.GetString("msgCalanderYearReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Billing Address.
        /// </summary>
        public static string msgChangeBillAddressTitleBox {
            get {
                return ResourceManager.GetString("msgChangeBillAddressTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the Billing Address?.
        /// </summary>
        public static string msgChangeBillingAddConfirm {
            get {
                return ResourceManager.GetString("msgChangeBillingAddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the Street Address?.
        /// </summary>
        public static string msgChangeStreetAddConfirm {
            get {
                return ResourceManager.GetString("msgChangeStreetAddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Street Address.
        /// </summary>
        public static string msgChangeStreetAddressTitleBox {
            get {
                return ResourceManager.GetString("msgChangeStreetAddressTitleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Code already exists.
        /// </summary>
        public static string msgCodeAlready {
            get {
                return ResourceManager.GetString("msgCodeAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid Customer Code.
        /// </summary>
        public static string msgCustomerCodeReq {
            get {
                return ResourceManager.GetString("msgCustomerCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid Customer Name.
        /// </summary>
        public static string msgCustomerNameReq {
            get {
                return ResourceManager.GetString("msgCustomerNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid Customer Type.
        /// </summary>
        public static string msgCustomerTypeReq {
            get {
                return ResourceManager.GetString("msgCustomerTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage codes must contain 5 numbers!..
        /// </summary>
        public static string msgDamageCodeNumberValidation {
            get {
                return ResourceManager.GetString("msgDamageCodeNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least one damage code.
        /// </summary>
        public static string msgDamageCodeReq {
            get {
                return ResourceManager.GetString("msgDamageCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage codes can only contain numbers.
        /// </summary>
        public static string msgDamageCodeValidation {
            get {
                return ResourceManager.GetString("msgDamageCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be Greater than End Date.
        /// </summary>
        public static string msgDateCompair {
            get {
                return ResourceManager.GetString("msgDateCompair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Record(s) Found :\n Cust:.
        /// </summary>
        public static string msgDateoutProcess {
            get {
                return ResourceManager.GetString("msgDateoutProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date/End Date cannot be blank.
        /// </summary>
        public static string msgDateReq {
            get {
                return ResourceManager.GetString("msgDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the dealer storage line item..
        /// </summary>
        public static string msgDealerError {
            get {
                return ResourceManager.GetString("msgDealerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully..
        /// </summary>
        public static string msgDeleteSuccessfully {
            get {
                return ResourceManager.GetString("msgDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id already exists..
        /// </summary>
        public static string MsgDuplicateEmailID {
            get {
                return ResourceManager.GetString("MsgDuplicateEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Name already exists..
        /// </summary>
        public static string MsgDuplicateUserName {
            get {
                return ResourceManager.GetString("MsgDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate VIN exists!.
        /// </summary>
        public static string MsgDuplicateVIN {
            get {
                return ResourceManager.GetString("MsgDuplicateVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid End Date..
        /// </summary>
        public static string msgEndDateReq {
            get {
                return ResourceManager.GetString("msgEndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an ending Invoice Number.
        /// </summary>
        public static string msgEndInvoiceReq {
            get {
                return ResourceManager.GetString("msgEndInvoiceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string msgErrorMessage {
            get {
                return ResourceManager.GetString("msgErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encoutered processing the outgate:.
        /// </summary>
        public static string msgErrorSecurity {
            get {
                return ResourceManager.GetString("msgErrorSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no records to export..
        /// </summary>
        public static string msgExportResultError {
            get {
                return ResourceManager.GetString("msgExportResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please search for a Billing Period to Modify.
        /// </summary>
        public static string MsgFindBillingPeriod {
            get {
                return ResourceManager.GetString("MsgFindBillingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the Find button to select a Customer and Modify!.
        /// </summary>
        public static string MsgFindCustomer {
            get {
                return ResourceManager.GetString("MsgFindCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Accounts Receivable Control GL Account Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceAccountReceivable {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceAccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Boston Auto port Storage GL Account Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceBostonAutoport {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceBostonAutoport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Credit Cost Centre Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceCostCenter {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Credit Cost Centre Number. Please check the Codes and Salesperson tables to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceCostCenterSales {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceCostCenterSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error determining whether or not the invoice contains a Diversifed and Outside Carrier split. The invoice line items have not been created!.
        /// </summary>
        public static string msgGenrateInvoiceDetermining {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceDetermining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the invoice number length, the invoice has not been created.
        /// </summary>
        public static string msgGenrateInvoiceLength {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting invoice number prefix, the invoice has not been created.
        /// </summary>
        public static string msgGenrateInvoicePrefix {
            get {
                return ResourceManager.GetString("msgGenrateInvoicePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the next invoice number, the invoice has not been created!.
        /// </summary>
        public static string msgGenrateInvoicePrefixNext {
            get {
                return ResourceManager.GetString("msgGenrateInvoicePrefixNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error looking up the Profit Centre Number. Please check the Codes table to ensure that the value exists!.
        /// </summary>
        public static string msgGenrateInvoiceProfitCenter {
            get {
                return ResourceManager.GetString("msgGenrateInvoiceProfitCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string MsgHidden {
            get {
                return ResourceManager.GetString("MsgHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Inserted Successfully.
        /// </summary>
        public static string msgInsertedCustomer {
            get {
                return ResourceManager.GetString("msgInsertedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Inserted Successfully!.
        /// </summary>
        public static string msgInsertedSuccessfully {
            get {
                return ResourceManager.GetString("msgInsertedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Inspection Date.
        /// </summary>
        public static string msgInspectionDateReq {
            get {
                return ResourceManager.GetString("msgInspectionDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one Inspection Type.
        /// </summary>
        public static string msgInspectionTypeReq {
            get {
                return ResourceManager.GetString("msgInspectionTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Location Name.
        /// </summary>
        public static string msgLocationNameReq {
            get {
                return ResourceManager.GetString("msgLocationNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Location Sub Type.
        /// </summary>
        public static string msgLocationSubTypeReq {
            get {
                return ResourceManager.GetString("msgLocationSubTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Location Type.
        /// </summary>
        public static string msgLocationTypeReq {
            get {
                return ResourceManager.GetString("msgLocationTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Zip Code.
        /// </summary>
        public static string msgLocationZipReq {
            get {
                return ResourceManager.GetString("msgLocationZipReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple open matches for the VIN that you entered! Please use the find window to find these records and make the correct adjustments..
        /// </summary>
        public static string msgMultipleVINProcessing {
            get {
                return ResourceManager.GetString("msgMultipleVINProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user added successfully.
        /// </summary>
        public static string msgNewUserAdded {
            get {
                return ResourceManager.GetString("msgNewUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string msgNo {
            get {
                return ResourceManager.GetString("msgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found !.
        /// </summary>
        public static string msgNoData {
            get {
                return ResourceManager.GetString("msgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Update.
        /// </summary>
        public static string msgNothingToUpdate {
            get {
                return ResourceManager.GetString("msgNothingToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Period Number.
        /// </summary>
        public static string msgPeriodNumberReq {
            get {
                return ResourceManager.GetString("msgPeriodNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VIN that you entered was not found in the Port Storage Vehicle table..
        /// </summary>
        public static string msgProcessingVINFound {
            get {
                return ResourceManager.GetString("msgProcessingVINFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted!.
        /// </summary>
        public static string MsgRecordDeleted {
            get {
                return ResourceManager.GetString("MsgRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated!.
        /// </summary>
        public static string MsgRecordUpdated {
            get {
                return ResourceManager.GetString("MsgRecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle was outgated successfully!.
        /// </summary>
        public static string msgSecurity {
            get {
                return ResourceManager.GetString("msgSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Perform GATE PASS Scan.
        /// </summary>
        public static string msgSecurityGatePass {
            get {
                return ResourceManager.GetString("msgSecurityGatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN for GATE PASS Scan too long, please RE-SCAN.
        /// </summary>
        public static string msgSecurityLongGatePass {
            get {
                return ResourceManager.GetString("msgSecurityLongGatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH, Please Click Process Vehicle.
        /// </summary>
        public static string msgSecurityMatch {
            get {
                return ResourceManager.GetString("msgSecurityMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO MATCH, Please Verify Vehicle Manually.
        /// </summary>
        public static string msgSecurityNoMatch {
            get {
                return ResourceManager.GetString("msgSecurityNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN for GATE PASS Scan too short, please RE-SCAN.
        /// </summary>
        public static string msgSecurityShortGatePass {
            get {
                return ResourceManager.GetString("msgSecurityShortGatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN for VEHICLE Scan too short, please RE-SCAN.
        /// </summary>
        public static string msgSecurityShortVIN {
            get {
                return ResourceManager.GetString("msgSecurityShortVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Perform VEHICLE Scan.
        /// </summary>
        public static string msgSecurityVEHICLEScan {
            get {
                return ResourceManager.GetString("msgSecurityVEHICLEScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select CodeType.
        /// </summary>
        public static string MsgSelectCodeType {
            get {
                return ResourceManager.GetString("MsgSelectCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a record to Continue.
        /// </summary>
        public static string msgSelectRecord {
            get {
                return ResourceManager.GetString("msgSelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a record to proceed..
        /// </summary>
        public static string MsgSelectUser {
            get {
                return ResourceManager.GetString("MsgSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Start Date..
        /// </summary>
        public static string msgStratDateReq {
            get {
                return ResourceManager.GetString("msgStratDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a starting Invoice Number..
        /// </summary>
        public static string msgStratInvoiceReq {
            get {
                return ResourceManager.GetString("msgStratInvoiceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box.
        /// </summary>
        public static string msgTitleMessageBox {
            get {
                return ResourceManager.GetString("msgTitleMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string msgTitleMessageBoxApprove {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string msgTitleMessageBoxDelete {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Processing Date Out.
        /// </summary>
        public static string msgTitleMessageBoxErrorSecurity {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxErrorSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple vehicles matching the entered VIN.
        /// </summary>
        public static string msgTitleMessageBoxMultipleVIN {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxMultipleVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Processed Successfully.
        /// </summary>
        public static string msgTitleMessageBoxSecurity {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Already In List.
        /// </summary>
        public static string msgTitleMessageBoxVehicleList {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxVehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Found.
        /// </summary>
        public static string msgTitleMessageBoxVehicleNotFound {
            get {
                return ResourceManager.GetString("msgTitleMessageBoxVehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Units.
        /// </summary>
        public static string msgTotalUnitReport {
            get {
                return ResourceManager.GetString("msgTotalUnitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update Common Location!.
        /// </summary>
        public static string msgUpdateCommonLocation {
            get {
                return ResourceManager.GetString("msgUpdateCommonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully..
        /// </summary>
        public static string msgUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("msgUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is last record..
        /// </summary>
        public static string msgVehicleLastRecord {
            get {
                return ResourceManager.GetString("msgVehicleLastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added this vehicle to the list..
        /// </summary>
        public static string msgVehicleListAlready {
            get {
                return ResourceManager.GetString("msgVehicleListAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is first record..
        /// </summary>
        public static string msgVehiclePrevRecord {
            get {
                return ResourceManager.GetString("msgVehiclePrevRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string msgview {
            get {
                return ResourceManager.GetString("msgview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter VIN Number and Customer Detail.
        /// </summary>
        public static string msgVINCustomerReq {
            get {
                return ResourceManager.GetString("msgVINCustomerReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a VIN.
        /// </summary>
        public static string msgVINReq {
            get {
                return ResourceManager.GetString("msgVINReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string MsgVisible {
            get {
                return ResourceManager.GetString("MsgVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortStorageVehicleDetailsInd.
        /// </summary>
        public static string PSIndicator {
            get {
                return ResourceManager.GetString("PSIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BillingID found to reset!.
        /// </summary>
        public static string ReqBillingID {
            get {
                return ResourceManager.GetString("ReqBillingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter Company Name..
        /// </summary>
        public static string ReqCompanyName {
            get {
                return ResourceManager.GetString("ReqCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID cannot be blank!.
        /// </summary>
        public static string ReqEmail {
            get {
                return ResourceManager.GetString("ReqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Invoice Type!.
        /// </summary>
        public static string ReqInvoiceType {
            get {
                return ResourceManager.GetString("ReqInvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Make!.
        /// </summary>
        public static string ReqMake {
            get {
                return ResourceManager.GetString("ReqMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Model!.
        /// </summary>
        public static string ReqModel {
            get {
                return ResourceManager.GetString("ReqModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank!.
        /// </summary>
        public static string ReqPassword {
            get {
                return ResourceManager.GetString("ReqPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Payment Method!.
        /// </summary>
        public static string ReqPaymentMethod {
            get {
                return ResourceManager.GetString("ReqPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name cannot be blank!.
        /// </summary>
        public static string ReqrUserName {
            get {
                return ResourceManager.GetString("ReqrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter VIN Number..
        /// </summary>
        public static string ReqVIN {
            get {
                return ResourceManager.GetString("ReqVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 17 Characters VIN can be Decoded..
        /// </summary>
        public static string ReqVIN17 {
            get {
                return ResourceManager.GetString("ReqVIN17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Year!.
        /// </summary>
        public static string ReqYear {
            get {
                return ResourceManager.GetString("ReqYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one role!.
        /// </summary>
        public static string RoleValidation {
            get {
                return ResourceManager.GetString("RoleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackPanelFixed_SP.
        /// </summary>
        public static string SPhome {
            get {
                return ResourceManager.GetString("SPhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port storage vehicle details.
        /// </summary>
        public static string TabVehicalDetails {
            get {
                return ResourceManager.GetString("TabVehicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabVehicleLocator.
        /// </summary>
        public static string TabVehicleLocator {
            get {
                return ResourceManager.GetString("TabVehicleLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Up/Delivered.
        /// </summary>
        public static string TextPickedUp {
            get {
                return ResourceManager.GetString("TextPickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string TextReceived {
            get {
                return ResourceManager.GetString("TextReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string TextRequested {
            get {
                return ResourceManager.GetString("TextRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerAdminUC.
        /// </summary>
        public static string UControlCustomerAdmin {
            get {
                return ResourceManager.GetString("UControlCustomerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PortStorageVehicleLocator.
        /// </summary>
        public static string UControlPSVehicleLoc {
            get {
                return ResourceManager.GetString("UControlPSVehicleLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehiclelocator.
        /// </summary>
        public static string UcontrolVehicleLocator {
            get {
                return ResourceManager.GetString("UcontrolVehicleLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid VIN!.
        /// </summary>
        public static string VINAlert {
            get {
                return ResourceManager.GetString("VINAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot Delete Current User!.
        /// </summary>
        public static string WarnDeleteCurrentUser {
            get {
                return ResourceManager.GetString("WarnDeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillingPeriodFind.
        /// </summary>
        public static string WinBillingFind {
            get {
                return ResourceManager.GetString("WinBillingFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeList.
        /// </summary>
        public static string WinCodeFind {
            get {
                return ResourceManager.GetString("WinCodeFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversified.
        /// </summary>
        public static string WinHomeTitle {
            get {
                return ResourceManager.GetString("WinHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportWindow.
        /// </summary>
        public static string WinReport {
            get {
                return ResourceManager.GetString("WinReport", resourceCulture);
            }
        }
    }
}
